services:
  postgres:
    image: postgres:16-alpine
    container_name: promohub-postgres
    environment:
      POSTGRES_DB: promohub_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - promohub-postgres-data:/var/lib/postgresql/data

volumes:
  promohub-postgres-data: